$(document).ready(function () {

    $('#supervOrder').live('click', function () {
        $('#contTable').html('<tr><td><p3><s> State Correspondence Certificate/ certificate of compliance (GOST B)</s>  - is a required document to confirm the product conformity with the established requirements of existing regulations. The company’s activities including products manufacture and sale in the territory of Republic of Belarus, as well as customs clearance of shipments shall be certified.<s> Certificate GOST B </s> allows you to carry the goods across the border of the Republic of Belarus and sell it through retail networks or use in manufacturing. In accordance with the Act of "According to estimation of requirements of technical regulations in the field of technical regulation and standardization", the certification can be both obligatory and voluntary.</p3><p3> The products subject to obligatory certification are determined by the List of products, services, personnel and other objects of conformity assessment, which are subject to obligatory conformity assessment in the Republic of Belarus <a href="#" id="pdf">here<a/>.</p3><p3> However, to increase the competitive advantage of your company through state confirmation of the proposed product, you may receive a <s> certificate of compliance </s on a voluntary basis, which is likely to excel your product worthy from the competitors.</p3><p3> Working with JSC KPD-service your will be able to define the required scheme of certification, allowing to receive the  <s> certificate of compliance </s in the shortest time and with minimal financial losses. In order to gain a  <s> correspondence certificate </s> with the manufacturer, the supplier or importer shall apply to the certification bodies and authorities, where there will be defined the scheme of certification depending on the applicant’s goals and product type. The experts of the company will provide the information on how to prepare a <s> certificate of conformity GOST B </s> at the simplified program.</p3><p3> Our highly qualified professionals are ready to provide the following services:</p3><ul><li> Advice service on certification issues in Belarus;</li><li> Work out the documentation package to get the certificate of compliance; </li><li> Your interests to get the <s> GOST B</s>.</li></ul><p3> KPD-service company, acting on the basis of legislation of the Republic of Belarus cooperates with the state certification authorities, the leading accredited laboratories, ensures high quality service and rapid delivery of services to obtain <s> certificate of compliance (GOST B)</s> in the Republic of Belarus.</p3></td></tr>');
        return false;
    });
    $('#pdf').live('click', function () {
        window.location.replace("http://www.gosstandart.gov.by/txt/Ob-podtv-sootv/docs/2010-289(016-069).pdf");
        return false;
    });
});

