//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class KpdResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal KpdResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.KpdResource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to о нас.
        /// </summary>
        internal static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес.
        /// </summary>
        internal static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сертификация в Госстандарте.
        /// </summary>
        internal static string certification {
            get {
                return ResourceManager.GetString("certification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контакты.
        /// </summary>
        internal static string contacts {
            get {
                return ResourceManager.GetString("contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сотрудничество.
        /// </summary>
        internal static string cooperation {
            get {
                return ResourceManager.GetString("cooperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to обратная связь.
        /// </summary>
        internal static string feedback {
            get {
                return ResourceManager.GetString("feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/themes/kpd/images/pic 1.gif.
        /// </summary>
        internal static string IEpic {
            get {
                return ResourceManager.GetString("IEpic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы там, где другие будут только завтра!.
        /// </summary>
        internal static string IEslogan {
            get {
                return ResourceManager.GetString("IEslogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логистика и сопровождение проектов.
        /// </summary>
        internal static string logistics {
            get {
                return ResourceManager.GetString("logistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/themes/kpd/images/logo-ru.png.
        /// </summary>
        internal static string logo_path {
            get {
                return ResourceManager.GetString("logo_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to новости.
        /// </summary>
        internal static string news {
            get {
                return ResourceManager.GetString("news", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to партнеры.
        /// </summary>
        internal static string partners {
            get {
                return ResourceManager.GetString("partners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/themes/kpd/images/pic-3.png.
        /// </summary>
        internal static string pic3 {
            get {
                return ResourceManager.GetString("pic3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/themes/kpd/images/pic-4.png.
        /// </summary>
        internal static string pic4 {
            get {
                return ResourceManager.GetString("pic4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/themes/kpd/images/pic-5.png.
        /// </summary>
        internal static string pic5 {
            get {
                return ResourceManager.GetString("pic5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/themes/kpd/images/pic-6.png.
        /// </summary>
        internal static string pic6 {
            get {
                return ResourceManager.GetString("pic6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/themes/kpd/images/copyright-in-cassandra.png.
        /// </summary>
        internal static string signature {
            get {
                return ResourceManager.GetString("signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/themes/kpd/images/slogan_ru.png.
        /// </summary>
        internal static string slogan {
            get {
                return ResourceManager.GetString("slogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to решения.
        /// </summary>
        internal static string solution {
            get {
                return ResourceManager.GetString("solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разрешение на применение Госпромнадзора.
        /// </summary>
        internal static string standard {
            get {
                return ResourceManager.GetString("standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Технический перевод.
        /// </summary>
        internal static string translation {
            get {
                return ResourceManager.GetString("translation", resourceCulture);
            }
        }
    }
}
